In [1]:
import pandas as pd
df = pd.read_csv("Wednesday.csv")
df['transit_timestamp'] = pd.to_datetime(df['transit_timestamp'])
morning_df = df[(df['transit_timestamp'].dt.time >= pd.Timestamp('07:00:00').time()) & 
                (df['transit_timestamp'].dt.time <= pd.Timestamp('09:00:00').time())]

In [7]:
morning_df

,transit_timestamp,station_complex_id,station_complex,borough,routes,payment_method,ridership,transfers,latitude,longitude,Georeference,itsuid,day,demand
23,2022-11-23 09:00:00,R254,110 St (6),M,6,omny,132,0,40.795021,-73.944252,POINT (-73.94425201416016 40.795021057128906),2022-11-23T09:00:00R254110 St (6)M6omny,Wednesday,0.0
30,2022-08-03 09:00:00,R302,"116 St (2,3)",M,"3,2",omny,133,11,40.802097,-73.949623,POINT (-73.94962310791016 40.80209732055664),"2022-08-03T09:00:00R302116 St (2,3)M3,2omny",Wednesday,398140.0
50,2023-05-10 08:00:00,J037,"121 St (J,Z)",Q,"J,Z",omny,68,5,40.700493,-73.828293,POINT (-73.82829284667969 40.70049285888672),"2023-05-10T08:00:00J037121 St (J,Z)QJ,Zomny",Wednesday,0.0
59,2023-04-12 07:00:00,R304,"125 St (2,3)",M,"3,2",omny,174,8,40.807755,-73.945496,POINT (-73.94549560546875 40.80775451660156),"2023-04-12T07:00:00R304125 St (2,3)M3,2omny",Wednesday,402321.0
65,2023-04-26 08:00:00,R306,"135 St (2,3)",M,"3,2",omny,331,0,40.814228,-73.940773,POINT (-73.9407730102539 40.81422805786133),"2023-04-26T08:00:00R306135 St (2,3)M3,2omny",Wednesday,393212.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1709619,2023-01-25 08:00:00,R419,Zerega Av (6),BX,6,omny,64,0,40.836487,-73.847038,POINT (-73.84703826904297 40.83648681640625),2023-01-25T08:00:00R419Zerega Av (6)BX6omny,Wednesday,0.0
1709635,2022-12-28 07:00:00,R419,Zerega Av (6),BX,6,omny,54,0,40.836487,-73.847038,POINT (-73.84703826904297 40.83648681640625),2022-12-28T07:00:00R419Zerega Av (6)BX6omny,Wednesday,0.0
1709645,2022-10-19 07:00:00,R419,Zerega Av (6),BX,6,metrocard,274,0,40.836487,-73.847038,POINT (-73.84703826904297 40.83648681640625),2022-10-19T07:00:00R419Zerega Av (6)BX6metrocard,Wednesday,0.0
1709649,2023-08-23 07:00:00,R419,Zerega Av (6),BX,6,metrocard,570,0,40.836487,-73.847038,POINT (-73.84703826904297 40.83648681640625),2023-08-23T07:00:00R419Zerega Av (6)BX6metrocard,Wednesday,0.0
1709660,2023-02-01 08:00:00,R419,Zerega Av (6),BX,6,omny,73,1,40.836487,-73.847038,POINT (-73.84703826904297 40.83648681640625),2023-02-01T08:00:00R419Zerega Av (6)BX6omny,Wednesday,0.0

In [2]:
lines = {
    "Line1": ['R192', 'R190', 'R188', 'R186', 'R185', 'R183', 'R182', 'R180', 'R178', 'R176',
              'R174', 'R173', 'R172', 'R170', 'R168', 'R164', 'R162', 'R160', 'N049', 'R154',
              'N060', 'R135', 'R133', 'R131', 'R129', 'N512', 'R125', 'R123', 'R119', 'R117', 'R116', 'R106', 'R103', 'R101'],

    "Line2": ['R336', 'R335', 'R334', 'R333', 'R332', 'R331', 'R330', 'R329', 'R328', 'R326', 'R325', 'R323', 'R322', 'R320',
              'R318', 'R316', 'R314', 'R312', 'R310', 'R261', 'R306', 'R304', 'R302', 'R301', 'R168', 'R161B', 'N060', 'R135',
              'N512', 'N094', 'N095', 'R111', 'R600', 'R602', 'R606', 'R608', 'R610', 'R617', 'R619', 'R621', 'R622', 'R635',
              'R636', 'R637', 'R639', 'R641', 'R643', 'R645'],
    # "Line3": [...],  # 若有更多线路，继续这样添加
}

# 从所有线路中找出中转站
all_stations = [station for sublist in lines.values() for station in sublist]
transfer_stations = {station for station in all_stations if all_stations.count(station) > 1}
print(all_stations)
print(transfer_stations)

['R192', 'R190', 'R188', 'R186', 'R185', 'R183', 'R182', 'R180', 'R178', 'R176', 'R174', 'R173', 'R172', 'R170', 'R168', 'R164', 'R162', 'R160', 'N049', 'R154', 'N060', 'R135', 'R133', 'R131', 'R129', 'N512', 'R125', 'R123', 'R119', 'R117', 'R116', 'R106', 'R103', 'R101', 'R336', 'R335', 'R334', 'R333', 'R332', 'R331', 'R330', 'R329', 'R328', 'R326', 'R325', 'R323', 'R322', 'R320', 'R318', 'R316', 'R314', 'R312', 'R310', 'R261', 'R306', 'R304', 'R302', 'R301', 'R168', 'R161B', 'N060', 'R135', 'N512', 'N094', 'N095', 'R111', 'R600', 'R602', 'R606', 'R608', 'R610', 'R617', 'R619', 'R621', 'R622', 'R635', 'R636', 'R637', 'R639', 'R641', 'R643', 'R645']
{'R168', 'N512', 'N060', 'R135'}

In [8]:
# 初始化一个空的需求字典
demands = {}

# 计算时间点的平均流量
def calculate_avg_ridership(station, line):
    times = [pd.Timestamp('07:00:00').time(), pd.Timestamp('08:00:00').time(), pd.Timestamp('09:00:00').time()]
    total = 0
    for time in times:
        total += morning_df[(morning_df['station_complex_id'] == station) & 
                            (morning_df['transit_timestamp'].dt.time == time)]['ridership'].sum()
    return total / len(times)

# 遍历每一条线路
for line, stations in lines.items():
    previous_demand = 0
    for station in stations:
        avg_ridership = calculate_avg_ridership(station, line)
        
        # 如果站点是中转站，考虑所有线路的平均乘客流量
        if station in transfer_stations:
            total_avg_ridership = sum([calculate_avg_ridership(station, route) 
                                       for route in lines.keys() if station in lines[route]])
        else:
            total_avg_ridership = avg_ridership

        # 计算需求值
        demand = 0.6 * previous_demand + total_avg_ridership
        demands[station] = demand
        
        # 更新 previous_demand
        previous_demand = demand

# 将计算的需求值添加到morning_df中
morning_df['demand'] = morning_df['station_complex_id'].map(demands)

# 获取一二号线的站点
line1_and_line2_stations = lines["Line1"] + lines["Line2"]

# 仅过滤出一二号线的数据
line1_and_line2_df = morning_df[morning_df['station_complex_id'].isin(line1_and_line2_stations)]

# 显示结果
print(line1_and_line2_df[['station_complex_id', 'demand']].drop_duplicates())

        station_complex_id         demand
30                    R302  204622.682687
59                    R304  198223.915589
65                    R306  199748.192648
154                   R333   71135.258667
343                   R619  276716.941341
...                    ...            ...
1639434               R106  184581.409371
1642846               R336   32338.666667
1646356               R111  916632.795569
1662716               R323  128306.008142
1678706               R637  186911.684292

[78 rows x 2 columns]

C:\Users\Xyic\AppData\Local\Temp\ipykernel_51944\3661473571.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  morning_df['demand'] = morning_df['station_complex_id'].map(demands)